site_name: 🤖 Megabots
features:
  - navigation.instant
  - navigation.tabs
  - navigation.sections

repo_url: https://github.com/momegas/megabots
repo_name: momegas/megabots
site_author: Megaklis Vasilakis
site_description: >-
  🤖 Megabots provides State-of-the-art, production ready LLM apps made mega-easy, 
  so you don't have to build them from scratch 🤯 Create a bot, now 🫵
copyright: Copyright &copy; 2023 Megaklis Vasilakis
# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started.md
      - Creating your site: creating-your-site.md
      - Contributing:
          - contributing/index.md
          - Reporting a bug: contributing/reporting-a-bug.md
          - Reporting a docs issue: contributing/reporting-a-docs-issue.md
          - Requesting a change: contributing/requesting-a-change.md
          - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
      - Guides:
          - Creating a reproduction: guides/creating-a-reproduction.md
  - Setup:
      - setup/index.md
      - Setting up navigation: setup/setting-up-navigation.md

theme:
  name: material
  logo: null
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
