# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: MegaBots - production ready LLM apps
site_url: https://momegas.github.io/megabots/
site_author: LightningRalf
site_description: >-
  🤖 State-of-the-art, production ready LLM apps made mega-easy, so you don't have to build them from scratch 🤯 
  Create a bot, now 🫵

# Repository
repo_name: momegas/megabots
repo_url: https://github.com/momegas/megabots

# Copyright
copyright: Copyright &copy; 2023 Megaklis Vasilakis


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotation
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/momegas/megabots
    #- icon: fontawesome/brands/gitter
    #  link: https://gitter.im/momegas/megabots
    #- icon: fontawesome/brands/docker
    #  link: https://hub.docker.com/r/momegas/megabots
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/megabots/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/megaklis.vasilakis
    - icon: fontawesome/brands/square-github
      link: https://github.com/momegas

# Page tree
nav:
  - Home:
    - Index: index.md
    - Quick start: 01-general/quick-start.md
    - Features overview:
      - Create a simple bot: 03-features/bot.md
      - Change the prompt: 03-features/prompt.md
      - Add memory to your bot: 03-features/memory.md
      - Connect a vector store: 03-features/vectorstores.md
      - Expose bot API: ""
      - Expose chatbot interface: ""

    - Community:
      - How to contribute: 05-contributing/doc-contributing.md
      - Ask a question🔗: https://github.com/momegas/megabots/discussions/categories/q-a
      - Join Discord🔗: https://discord.gg/2RUwt43U58

  - Cloud:
    - Getting started: cloud.md
   

copyright: |
  &copy; 2023 <a href="https://github.com/momegas" target="_blank" rel="noopener">Megaklis Vasilakis</a>